'use client';

import { useState, useCallback } from 'react';
import styles from '../admin.module.css';
import Toast from '@/components/admin/Toast';

const reportStats = [
  { label: 'Total Reports',  value: '284', meta: '+12 this month',      icon: '📊', metaClass: styles.statMetaGreen  },
  { label: 'Pending Review', value: '38',  meta: '6 urgent',            icon: '⏳', metaClass: styles.statMetaOrange },
  { label: 'Completed',      value: '246', meta: '87% completion rate', icon: '✅', metaClass: styles.statMetaGreen  },
];

const reports = [
  { title: 'Fall 2023 Enrollment Summary',    type: 'Enrollment', generatedBy: 'Admin Dept',    date: 'Oct 24, 2023', status: 'Completed' },
  { title: 'Faculty Performance Review Q3',   type: 'Faculty',    generatedBy: 'Dr. Smith',     date: 'Oct 22, 2023', status: 'Pending'   },
  { title: 'Department Budget Analysis',       type: 'Finance',    generatedBy: 'Prof. Johnson', date: 'Oct 20, 2023', status: 'Completed' },
  { title: 'Student GPA Distribution Report', type: 'Academic',   generatedBy: 'Admin Dept',    date: 'Oct 18, 2023', status: 'Completed' },
  { title: 'Course Completion Rates Fall 23', type: 'Academic',   generatedBy: 'Prof. Malan',   date: 'Oct 15, 2023', status: 'Pending'   },
  { title: 'New Student Orientation Report',  type: 'Enrollment', generatedBy: 'Admin Dept',    date: 'Oct 10, 2023', status: 'Completed' },
];

function initials(name) {
  return name.split(' ').map((w) => w[0]).join('').slice(0, 2);
}

export default function ReportsPage() {
  const [toast, setToast] = useState(null);
  const closeToast = useCallback(() => setToast(null), []);

  function handleExport() {
    setToast('Report exported successfully');
  }

  return (
    <main className={styles.pageContent} style={{ display: 'block' }}>

      {/* Stat Cards */}
      <div className={styles.statCardsRow} style={{ marginBottom: '24px' }}>
        {reportStats.map((s) => (
          <div className={styles.statCard} key={s.label}>
            <div className={styles.statCardTop}>
              <span className={styles.statLabel}>{s.label}</span>
              <span className={styles.statIconBox}>{s.icon}</span>
            </div>
            <div className={styles.statValue}>{s.value}</div>
            <div className={`${styles.statMeta} ${s.metaClass}`}>
              <span>{s.meta.split(' ')[0]}</span>
              {' ' + s.meta.split(' ').slice(1).join(' ')}
            </div>
          </div>
        ))}
      </div>

      {/* Reports Table */}
      <div className={styles.card}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <div>
            <div className={styles.cardTitle} style={{ fontSize: '22px' }}>Reports</div>
            <div className={styles.cardSubtitle} style={{ marginBottom: 0 }}>
              View analytics and generated reports
            </div>
          </div>
          <button className={styles.btnPrimary} onClick={handleExport}>
            ↓ Export Report
          </button>
        </div>

        <div className={styles.tableWrap}>
          <table>
            <thead>
              <tr>
                <th className={styles.tableHeader}>Report Title</th>
                <th className={styles.tableHeader}>Type</th>
                <th className={styles.tableHeader}>Generated By</th>
                <th className={styles.tableHeader}>Date</th>
                <th className={styles.tableHeader}>Status</th>
                <th className={styles.tableHeader}></th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr className={styles.tableRow} key={r.title}>
                  <td className={styles.tableCell}>
                    <div className={styles.reqType}>{r.title}</div>
                  </td>
                  <td className={styles.tableCell}>
                    <span className={styles.badge} style={{ background: 'var(--primary-light)', color: 'var(--primary)' }}>
                      {r.type}
                    </span>
                  </td>
                  <td className={styles.tableCell}>
                    <div className={styles.submitterCell}>
                      <div className={styles.avatar}>{initials(r.generatedBy)}</div>
                      {r.generatedBy}
                    </div>
                  </td>
                  <td className={styles.tableCell} style={{ color: 'var(--text-light)', whiteSpace: 'nowrap' }}>
                    {r.date}
                  </td>
                  <td className={styles.tableCell}>
                    <span
                      className={styles.statusBadge}
                      style={r.status === 'Completed'
                        ? { background: 'var(--green-light)', color: 'var(--green)' }
                        : { background: 'var(--yellow-light)', color: 'var(--yellow)' }}
                    >
                      {r.status}
                    </span>
                  </td>
                  <td className={styles.tableCell}>
                    <button className={styles.moreBtn} onClick={() => setToast(`Downloading: ${r.title}`)}>⋯</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {toast && <Toast message={toast} onClose={closeToast} />}
    </main>
  );
}
